### ISSUE TITLE
Add support for projects hosted on sourcehut (sr.ht)

### ISSUE THREAD

**Issue by tsdh** [deps-rs/deps.rs#115]
Some testing suggests that deps.rs supports projects hosted on github and gitlab but not my project's which are on [sourcehut](https://sr.ht/).  At least, when specifying a repository path such as https://deps.rs/repo/sourcehut/~tsdh/swayr or https://deps.rs/repo/srht/~tsdh/swayr, I get the error "Could not parse repository path".

The actual repository is https://git.sr.ht/~tsdh/swayr.

**Comment by Feliix42** [comment]
This has been fixed by #117.
