### ISSUE TITLE
Failed to analyze `wasmtime` repo

### ISSUE THREAD

**Issue by repi** [deps-rs/deps.rs#125]
This fails with "Failed to analyze repository - The repository you requested might be structured in an uncommon way that is not yet supported."

https://deps.rs/repo/github/bytecodealliance/wasmtime

Not sure what setup the [`wasmtime` repo](https://github.com/bytecodealliance/wasmtime) has that is not supported, it is a workspace in the root but a workspace that is a package also, maybe that is it?

**Comment by DJMcNab** [comment]
This appears to now be resolved
