### ISSUE TITLE
Failed to analyze repository `lingua`

### ISSUE THREAD

**Issue by pemistahl** [deps-rs/deps.rs#144]
I've just released the new version 1.3.3 of my crate `lingua`. Deps.rs suddenly does not work anymore. In the past, there was never a problem with analyzing the dependencies and showing the correct badge in the README of the project. Can you tell what's wrong? Thank you very much.

https://github.com/pemistahl/lingua-rs

https://deps.rs/crate/lingua/1.3.3

**Comment by paolobarbolini** [comment]
https://deps.rs/crate/lingua still redirects to 1.3.2 so I guess the crates.io-index isn't getting updated

**Comment by robjtede** [comment]
this works locally and finds 1.3.3

**Comment by pemistahl** [comment]
@paolobarbolini Do you mean the deps.rs server or the crates.io server? I assume it's the former. Is there anything you can do about it?

**Comment by cecton** [comment]
Restart in progress... sorry for the delay!

**Comment by cecton** [comment]
It seems to have worked. I guess there is some kind of caching issue somewhere... We should keep that in mind if the problem happens again in the future.

**Comment by pemistahl** [comment]
@cecton Thank you very much for your help. :)
