### ISSUE TITLE
The service seems to have stopped working

### ISSUE THREAD

**Issue by ljedrz** [deps-rs/deps.rs#156]
I think I first noticed it yesterday, and thought that it was temporary, but it seems that docs can't be obtained for any crate right now, and the badges are broken too:

<img src="https://user-images.githubusercontent.com/3750347/179217237-0f9e7e50-49a9-4052-80aa-924b0764438a.png" height="200" />

**Comment by rukai** [comment]
Looks like we hit the same problem again

**Comment by robjtede** [comment]
So that it only takes 1 maintainer to fix this issue, folks finding this issue could open a PR with just a `cargo update` run in it.

**Comment by Feliix42** [comment]
Did we have any success yet in investigating the problem on the deployment server (i.e., logs)?

**Comment by Feliix42** [comment]
The service is now up and running again. Closing this issue to focus discussions in #106.
