### ISSUE TITLE
RustCrypto repos: Failed to analyze repository

### ISSUE THREAD

**Issue by tarcieri** [deps-rs/deps.rs#162]
The deps.rs badges were previously working for us, but now across all repos we get:

> # Failed to analyze repository
> The repository you requested might be structured in an uncommon way that is not yet supported.

e.g. https://deps.rs/repo/github/RustCrypto/traits

**Comment by paolobarbolini** [comment]
It's working for my local instance, so I guess something broke on the server. I hope we're not all of the sudden annoying GitHub with all of the `raw.githubusercontent.com` requests we send in order to analyze repositories :thinking:

**Comment by paolobarbolini** [comment]
I've had a chance to look into the production logs and the requests seem to timeout after 5 seconds.

**Comment by Feliix42** [comment]
Unfortunately, this is an intermittent issue that comes up every few weeks which we are currently debugging. Please let us know in #106 if you notice this happening again, for the moment it seems to be working. :)
