### ISSUE TITLE
[Question] Badge without version?

### ISSUE THREAD

**Issue by saona-raimundo** [deps-rs/deps.rs#196]
Thanks for the effort!!

Currently, the link for the badge is `https://deps.rs/crate/<name>/<version>/status.svg`

Would you consider making a link that is version independent?

This is possible for some information in crates.io. For example, for the current version of a crate, we have `https://img.shields.io/crates/v/<name>.svg`

**Comment by robjtede** [comment]
It's not terribly well documented but it's possible to use "latest" in the `<version>` position. Eg: <https://deps.rs/crate/time/latest/status.svg>/

**Comment by saona-raimundo** [comment]
Thank you for the answer!

To be consistent, would you consider allowing the link `https://deps.rs/crate/time/latest` to be valid?
Currently, a link to the latest version of a crate is only `https://deps.rs/crate/time`.
