### ISSUE TITLE
Integrate with cargo-audit to capture security issues

### ISSUE THREAD

**Issue by alex** [deps-rs/deps.rs#20]
https://github.com/rustsec/cargo-audit

It might make sense to use the underlying libraries behind cargo-audit instead of it directly.

**Comment by srijs** [comment]
Hey, thanks, this sounds like a great idea!

Integrating with https://github.com/RustSec/advisory-db looks relatively straight-forward to me.

**Comment by Feliix42** [comment]
This is already implemented, so the issue can be closed.
