### ISSUE TITLE
ed25519-dalek version is stuck on 1.0.1

### ISSUE THREAD

**Issue by tarcieri** [deps-rs/deps.rs#201]
<img width="1002" alt="Screenshot 2023-08-14 at 3 56 38 PM" src="https://github.com/deps-rs/deps.rs/assets/797/39b7d4c5-2408-4069-964e-7af27ea999b6">

The latest version is 2.0.0, which has been out for several days:

https://crates.io/crates/ed25519-dalek/2.0.0

**Comment by robjtede** [comment]
related to #106 but this specific issue seems to be resolved
