### ISSUE TITLE
Failed to analyze repository

### ISSUE THREAD

**Issue by hoijui** [deps-rs/deps.rs#210]
See it here:
<https://deps.rs/repo/github/hoijui/projvar>

My guess is, that it is because of [this dependency line](
https://github.com/hoijui/projvar/blob/8dc3641749752c38b92459e9562402700b77d130/Cargo.toml#L49):

```toml
cli_utils = { version = "0.6", package = "cli_utils_hoijui" }
```

As it is probably the most unusual one.

Is it somehow possible to get to more info why the analysis failed?

**Comment by hoijui** [comment]
Same happens with this crate, which has the same dependency line like the one above:
<https://deps.rs/repo/github/hoijui/repvar>

**Comment by szepeviktor** [comment]
Seems like every repo fails: https://deps.rs/

**Comment by fluxxcode** [comment]
> Seems like every repo fails: https://deps.rs/
> 
> @paolobarbolini Could you help?

I think this is a new bug. Yesterday or the day before yesterday everything was still working 🤔

**Comment by iganev** [comment]
As of today all of my repositories report the same error at deps.rs

**Comment by hoijui** [comment]
So since mid February (possibly months before that) this service is practically useless, and only four people care?
How can that be?

**Comment by robjtede** [comment]
duplicate of #106

**Comment by robjtede** [comment]
This is a known issue and the team have certain workarounds in place, clearly they're not good enough yet but we're working on it.
