### ISSUE TITLE
Allow to retrieve badge for latest version of crate

### ISSUE THREAD

**Issue by DoumanAsh** [deps-rs/deps.rs#34]
For example `https://deps.rs/crate/yukikaze` would get me latest crate version
While `https://deps.rs/crate/yukikaze/status.svg` would get me nowhere so user would need to always point to particular version which may not be convenient

**Comment by DoumanAsh** [comment]
@mitchtbaum Yeah, I knew about work-around, but it is only working for github repos, while my lib is on gitlab 😄 

I actually wanted to fix it myself, but just totally forgot about it.
Wanna make this PR?

**Comment by mitchtbaum** [comment]
That's a bit outside my skill range.  I can read code, but have something like dyslexia when it comes to writing it.

**Comment by Feliix42** [comment]
Currently, we support gitlab, github and bitbucket as repository hosts. So this should be resolved I guess. :)

**Comment by robjtede** [comment]
I'd still like to see either: `https://deps.rs/crate/{name}/*/status.svg` or `https://deps.rs/crate/{name}/latest/status.svg`

**Comment by tsdh** [comment]
I'd also very much like to have a way to show a badge of the latest released version on crates.io, especially since I cannot use deps.rs with my repos since those are on [sourcehut](https://sr.ht) which is not (yet) supported (see #115).
