### ISSUE TITLE
Could not retrieve popular items error

### ISSUE THREAD

**Issue by kornelski** [deps-rs/deps.rs#38]
The https://deps.rs homepage appears to be down:

<img width="1030" alt="Screenshot 2019-08-10 at 02 10 05" src="https://user-images.githubusercontent.com/72159/62815697-0c343980-bb14-11e9-9d9f-c0e45fe06150.png">

**Comment by Enet4** [comment]
As reported in [this comment](https://github.com/deps-rs/deps.rs/issues/41#issuecomment-608017536) from #41, the front page stopped working once crates.io started rejecting requests without a user agent, which right now is only being passed in some of the requests made by the server. I can provide the necessary changes once #51 lands.
