### ISSUE TITLE
Failed to analyze repository

### ISSUE THREAD

**Issue by est31** [deps-rs/deps.rs#41]
Not sure when it started, but since some time, it's showing a "dependencies unknown" badge and if you visit the site, you are getting a "Failed to analyze repository" error. I can observe it on all of my own projects I've tried and it seems that this repo's deps.rs badge is affected too.

![Screenshot_20200402_123952](https://user-images.githubusercontent.com/8872119/78240266-0f36cc80-74df-11ea-868a-48a4d060991e.png)

![Screenshot_20200402_124014](https://user-images.githubusercontent.com/8872119/78240301-1cec5200-74df-11ea-861a-7597a59208e1.png)

**Comment by dekellum** [comment]
I'm seeing this too with my repros (body-image, blocking-permit, etc.). Might this be due to my recent commits of Cargo.lock in the new Cargo v2 lock format?

**Comment by est31** [comment]
> Might this be due to my recent commits of Cargo.lock in the new Cargo v2 lock format?

Lewton as well as this repo have it too and they use the old Cargo.lock format.

According to @eijebong the issue might be that it talks to the crates.io API without specifying an user agent, something the crates.io team started banning in recent times.

**Comment by Eijebong** [comment]
There are multiple issues. First one is the user agent, second one is a double `/` in some requests to github that makes it return 301 which deps.rs doesn't support. Third one is rustsec being so outdated it doesn't match the crates.io API anymore. I stopped there because updating rustsec is non trivial.

Plus there is #33

**Comment by Feliix42** [comment]
This seems to be due to a bug in the link generation for the request from Github, which results in a `301 Redirect` status code that the http client cannot handle at the moment.

#57 should fix this issue.
