### ISSUE TITLE
To move or not to move deps.rs to deps.rm.rs (decide before 27/01/2021)

### ISSUE THREAD

**Issue by cecton** [deps-rs/deps.rs#43]
As everybody knows already from #40, the project will now be maintained by everybody who wants.

I proposed myself to host it on deps.rm.rs but we could also take deps.rs. Please note that the price will be around $34. I don't personally want to pay for it by myself but I would agree on sharing the cost.

Please leave a comment if you prefer to keep deps.rs and pay for it or if it is okay to move it to deps.rm.rs.

(rm.rs is owned by myself. I started recently using it for https://yewprint.rm.rs)

**Comment by cecton** [comment]
cc @enet4 @robjtede @paolobarbolini @dcjanus @berkus

**Comment by cecton** [comment]
(Please also let us know if you want to be added as maintainer)

**Comment by cecton** [comment]
(I have added everybody. Just ignore if you dont want to be part of it)

**Comment by robjtede** [comment]
I'd be willing to put up a share of the cash for the domain when we've made some progress. I feel that using your domain @cecton as an in-progress staging area would be good for the time being.

**Comment by Enet4** [comment]
Thank you for bringing this up, @cecton. While I am not a major stakeholder, I believe that a service such as deps.rs is immensely beneficial to the Rust community, so I hope that eventually we'll manage to resolve the matters of hosting and funding. In the meantime however, having the temporary deps.rm.rs domain to keep the upstream version of the software is perfectly acceptable, and should at least set aside one of the current blockers.

> (Please also let us know if you want to be added as maintainer)

I would like to assist in this driving force of making deps reliable again. With or without the role of maintainer, you can also count on me.

**Comment by Feliix42** [comment]
I'd also be willing to contribute a small share for the domain cost, but we can also consider using some sort of crowd-funding to finance the fixed costs.

I agree with @robjtede that the `deps.rm.rs` domain would be a nice staging area and also a suitable fallback, but the original domain is probably a little snappier and easier to remember. :)

**Comment by berkus** [comment]
I'm fine to pay for deps.rs if needed.

**Comment by berkus** [comment]
> I'd be willing to put up a share of the cash for the domain when we've made some progress.

Is there any good tool for collecting contributions that we could then split into maintenance and other costs? Something like GitHub Sponsors or team patreon, or infinitely running indiegogo?

We could just set up contributions there and pay from that lot. There must be something usable!

**Comment by cecton** [comment]
Yes I just checked GitHub Sponsors I think that can work. We can create a sponsor account for the organization deps-rs I think

**Comment by cecton** [comment]
I will investigate

**Comment by cecton** [comment]
I'm closing this ticket as we have solved the problem.

@robjtede is now the new owner of deps.rs. He is the one paying for it so I suggest that **everybody who really wanted to keep the deps.rs domain sponsors @robjtede for $1**. With 2 people sponsoring him it's already enough to cover entirely the expense equally and fairly.

Thanks a lot to Rob for doing this for all of us and deps.rs users in general.

**Comment by cecton** [comment]
(The reason why we didn't make a collective is because it was complicated, we need an organization, bank account, stuff...)

**Comment by berkus** [comment]
Totally, as long as there's a dead man switch for contingencies we should be good.
