### ISSUE TITLE
Internal communication

### ISSUE THREAD

**Issue by Feliix42** [deps-rs/deps.rs#45]
Now that a new team is forming to maintain the project I was wondering if we want to use some external service for communication to have a platform to discuss possible changes or ideas. What do you think about this? Would that make sense or do you think communication using issues & PRs is enough?

As for possible communication channels I can think of (in the order I prefer them):
- Matrix (easy to use and thanks to federation you probably don't need to make an account specifically for this if you already have one)
- Discord
- [gitter.im](https://gitter.im/) (kind of dated by now but still preferred by some people)
- Mailing lists (just don't please)

**Comment by Enet4** [comment]
I am already familiar with Gitter, and I certainly don't mind that we use it. Matrix should be fine as well, so long as it isn't too hard to set up and use.

I agree that mailing lists wouldn't serve us well. Unless I'm overlooking something, we would hardly be better off than just using this issue tracker. :)

**Comment by DCjanus** [comment]
The most commonly used IM for me is Telegram, and sometimes I'll use discord. Matrix and gitter is ok, but mailing list is dinosaur to me.

**Comment by robjtede** [comment]
I'd vote for either Matrix or asking the rust community discord for a deps.rs channel.

**Comment by Enet4** [comment]
Unless I interpreted the preferences so far (would we need a "meh" column?), we seem to be inclined towards either Matrix or Discord. Some collaborators are yet to state their opinion, but here's the table so far. It would be nice to have this sorted out by the time #53 is merged.

service | ayes | nays
-------- | ---- | -----
Matrix | 3 | 0
Rust Community Discord | 3 | 0
Telegram | 1 | 0 
Gitter | 3 | 1

**Comment by robjtede** [comment]
I took the liberty of creating a matrix room: https://matrix.to/#/!eStlHjUHzmxzxWDIWW:matrix.org?via=matrix.org (or just search for deps.rs in the room search).

Of course nothing stops us changing at a later date but I'm certainly interested to see how matrix works for us.

**Comment by robjtede** [comment]
@cecton will you join the matrix chat? A point about sponsors was brought up there.

**Comment by cecton** [comment]
@berkus @DCjanus I think we only miss you two now on the channel

**Comment by berkus** [comment]
I'm constantly on Telegram, other services are hit-and-miss (I tend to start them but then forget to check). Matrix is probably the least popular of those, lack of good clients and inability to keep a tab always running for it makes it hard.

**Comment by Feliix42** [comment]
You can just pin the `element.io` tab in firefox and probably in other browsers, too. :)

**Comment by berkus** [comment]
Yeah I just looked at what's needed to build fractal and cried.

i'll probably stick element.io tab somewhere but if my tab auto-discard kills it i might miss some messages.

**Comment by berkus** [comment]
But it got me curious, native matrix client in rust... I ought to try it out!

**Comment by cecton** [comment]
I really have no opinion on the choice of the chatting program. I guess if the majority voted for Matrix we should try that...

> You can just pin the `element.io` tab in firefox and probably in other browsers, too. :)

That's what I do

**Comment by berkus** [comment]
```
  --- stderr
  tar: Error opening archive: Failed to open '/Users/berkus/Hobby/Rust/fractal/_build/target/cargo-home/git/checkouts/gettext-rs-990f4befadcf3bba/61938b9/gettext-sys/gettext-0.19.8.1.tar.xz'
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1
```

it's that bad.

**Comment by berkus** [comment]
We're all in the matrix now and Morpheus can close this ticket?

**Comment by robjtede** [comment]
Congrats on taking the red pill ^^
