### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by robjtede** [deps-rs/deps.rs#46]
We've had a good experience with actix-web using GitHub Actions but I see there's a travis config here already.

Lets spec out the goals for the CI, talking points:
- [ ] security audit
- [ ] tests
- [ ] deployments (stagings/prod)
- [ ] other

**Comment by jamiebrynes7** [comment]
I've also had good experiences with GitHub Actions (and with [`actions-rs`](https://github.com/actions-rs)). I'd generally be in favor of porting the CI from Travis to GitHub Actions (I've done so for most of my personal projects).

For example there are pre-built actions for:

- [`cargo audit`](https://github.com/actions-rs/audit-check) for security vulnerability checks. 
- code coverage with [`tarpaulin`](https://github.com/actions-rs/tarpaulin) or [`grcov`](https://github.com/actions-rs/grcov)
- [`clippy` lints](https://github.com/actions-rs/clippy-check) that leave comment in PRs

I'd be happy to drive this effort forward 😄

**Comment by Feliix42** [comment]
Maybe we should wait to see what @cecton thinks about this as she wanted to take care of the DevOps setup behind the repository and the deployment to Heroku via CI/CD. :)

**Comment by jamiebrynes7** [comment]
Sure thing, I'll pause the work in https://github.com/deps-rs/deps.rs/pull/49 and defer to her 👍

**Comment by cecton** [comment]
I think the proposal is great! We can move to GitHub Actions right away. Travis CI keeps breaking for my OSS projects so I'm also migrating some of them recently. :disappointed: 

> deployment to Heroku via CI/CD. :)

It's just for CD that I have a plan but not with Heroku, I have a k8s cluster which I can use. (But maybe I will give a try first with Qovery because I'm curious...) But I'm open to any proposition :slightly_smiling_face:

**Comment by Feliix42** [comment]
> > deployment to Heroku via CI/CD. :)
> 
> It's just for CD that I have a plan but not with Heroku, I have a k8s cluster which I can use. (But maybe I will give a try first with Qovery because I'm curious...) But I'm open to any proposition 🙂

Ah yes, I should've made that clearer, the original deployment was via Heroku. I'm open for anything. :)

**Comment by cecton** [comment]
We now have staging that is deployed automatically on http://staging.deps.rs/ We need to test it thoroughly to make sure everything is working properly.

I'm not sure we need a staging at all. I think it would be best to have a preview on every PR? Let me know what you think. cc all

**Comment by Enet4** [comment]
> I'm not sure we need a staging at all. I think it would be best to have a preview on every PR? Let me know what you think. cc all

How would this be handled for multiple PRs? If with the current setup we can afford for an independent container and subdomain for each active pull request, then that sounds quite interesting.

**Comment by robjtede** [comment]
In an idea world the main branch is always deployable so a system where PRs have a deployment preview would be fantastic. (Bearing in mind security conerns, of course.)

**Comment by kid** [comment]
> > I'm not sure we need a staging at all. I think it would be best to have a preview on every PR? Let me know what you think. cc all
> 
> How would this be handled for multiple PRs? If with the current setup we can afford for an independent container and subdomain for each active pull request, then that sounds quite interesting.

That should not be too much of an issue, the k8s manifests can be tweaked to explicitly create a wildcard certificate, and then use it when deploying `pr-xx.deps.rs`

Resources utilization might be an issue however, the current staging container is using 1 Gb of memory right now, does it needs that much?

**Comment by robjtede** [comment]
I think we're in a good place for CI and CD now. More specific future issues can have their own issue.
