### ISSUE TITLE
Fixed Rust Toolchain version?

### ISSUE THREAD

**Issue by Feliix42** [deps-rs/deps.rs#48]
As we just discussed in #44, the project is currently running on a Nightly toolchain. There's nothing wrong with that, but to avoid having a broken build out of nowhere we should either lock on a specific nightly version that is guaranteed to work or look into whether we can somehow move to stable easily.

I'm going to take a look and see how extensive the use of nightly-only features is.

**Comment by robjtede** [comment]
AFAICT it's just maud (HTML templating) that's nightly only. 

I'm fine with nightly fixed for now but would very much like to move to stable.

**Comment by jamiebrynes7** [comment]
If its the case that `maud` is the only nightly dependency, we may be able to move to stable soon if this milestone is still up-to-date. https://github.com/lambda-fairy/maud/milestone/1

**Comment by Feliix42** [comment]
lambda-fairy/maud#219 moved the project to stable so we just have to wait for the next release. Should we still fix on a specific nightly version until then or are we just going to hope that there are no breaking changes to `proc_macro`s?

**Comment by paolobarbolini** [comment]
If they don't plan to make a new release soon we could also temporarily import it from git
