### ISSUE TITLE
Link to RustSec CVEs for insecure crates

### ISSUE THREAD

**Issue by paolobarbolini** [deps-rs/deps.rs#75]
At the moment when an insecure crate is listed there's no easy way of knowing what's the security vulnerability and which versions are effected.

This could be implemented by making the ![screenshot.png](https://user-images.githubusercontent.com/6215781/98233446-58606a80-1f5f-11eb-992b-cd3bc201f50b.png) button into a link.

**Comment by Feliix42** [comment]
I'm currently looking into this (and I may bump the `rustsec` crate to 0.22 in the process if it's not too much of a pain) and I'm left with one question:

The `Advisory` struct ([docs](https://docs.rs/rustsec/0.22.2/rustsec/advisory/struct.Advisory.html)) has a [`Metadata`](https://docs.rs/rustsec/0.22.2/rustsec/advisory/metadata/struct.Metadata.html) member which contains all relevant info from the database, but no direct link to the database entry on github. The optional url field instead points to the page, where the vulnerability was initially reported. So I could either see us reconstructing the links by hand (meh) or add a section to the bottom of the page explaining the vulnerabilities. The `Advisory` struct even has a `description_html` function for that.

**Comment by paolobarbolini** [comment]
Another option would be to link to rustsec.org, but I think it gets updated manually so a new advisory may take a few days before it appears there.

**Comment by dekellum** [comment]
If you have the information, it would be nice if in the deps listing, there was some distinction made between: a vulnerability that is not fixed in any version of the dep available to the crate (e.g. remains unfixed or is only fixed in a version beyond the version range of the dependency) and a vulnerability that has since been fixed in a release that is available to the crate (e.g. `cargo update` will fix it).

**Comment by est31** [comment]
A link to the issue won't work if there are multiple issues. Better would be to link to a security report page/section of that specific dependency. That section would then include a html-ified version of a cargo-audit report.
