### ISSUE TITLE
RFC: git PR bot to bump outdated dependencies

### ISSUE THREAD

**Issue by sassman** [deps-rs/deps.rs#92]
I wanted to start a little discussion if the following proposal is out of scope for the project or if it would be worth to explore further.

## Starting point
For other languages than rust, [GitHub has this service](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates) that creates a PR with a version bump of the dependency(-ies) that are treated as insecure and outdated.

## Proposal
IMO that would go quite well with deps.rs from a semantically view point. So I imagine a GitHub independent bot like feature that would create PRs for dependencies that are outdated. Or whenever a new version is published on crates.io all depending crates would receive a PR to bump their version.

## Rationale
The rationale behind would be to simplify the upgrade process for other crate owner to a simple "Merge PR" and on the other hand a git hosting provider independent nursery could be provided to the community.

Curious if that would be of help to someone or not?

**Comment by cecton** [comment]
Pretty sure I saw dependabot working on Rust projects. What is not working exactly?

**Comment by robjtede** [comment]
I have it working on one of my repos: https://github.com/robjtede/sup-decode/pull/34. Gives nice changelog snippets and everything.

**Comment by sassman** [comment]
Was not aware of it. Looks pretty awesome. Thanks

**Comment by cecton** [comment]
So we close it?

I don't want to be rude 😅  It happens to me all the time to have a great idea only to realize that someone stole it to me in the past before I had it.

Any idea on how to improve this project would be welcome so don't hesitate. The only one I had is to make a dark theme.

**Comment by sassman** [comment]
Sure let's close it. I'm glad this problem got already solved elsewhere.
