### ISSUE TITLE
Support rust code in folder within repo root

### ISSUE THREAD

**Issue by Cldfire** [deps-rs/deps.rs#95]
I went to see if I could grab a deps.rs badge for a project of mine (https://github.com/Cldfire/minecraft-status) and it appears that currently there's no way for me to tell deps.rs that the rust code is inside of the `rust` folder, and not at the repo root.

(See https://deps.rs/repo/github/cldfire/minecraft-status)

EDIT: note that I have since created a workspace at the root of the above repo, so this issue no longer applies to me specifically

**Comment by Feliix42** [comment]
Yes, this is something that we cannot handle at the moment. I could imagine that we add a configuration file that gets placed in the repository root to define things like the path to the crate root. Alternatively we could tweak the URL to have something like `https://deps.rs/repo/github/cldfire/minecraft-status/path/[...]`, which is probably the more elegant solution.
